### ISSUE TITLE
Não é para mostrar essa seleção de Digital e Físico

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#107]
**Descrição:**
Não é para mostrar essa seleção de Digital e Físico

**Passos Para Reproduzir:**
Criar documento

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/133468209-3b872aab-3824-4808-b9ac-5b54f5f0bd8f.png)

**Comment by wendell-codata** [comment]
A remoção de digital ou físico pode ser feital através do menu Ferramentas -> Configuração de Cadastro, selecionar no combo o item Eletronico e colocar como obrigatório, conforme abaixo:
![Eletronico](https://user-images.githubusercontent.com/84041326/134067695-7bdc9bfc-6fc0-4606-92a6-9a21d12b5358.png)
