### ISSUE TITLE
 Esconder a opção "Arquivos Auxiliares"

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#109]
**Descrição:**
 Esconder a opção "Arquivos Auxiliares"

**Passos Para Reproduzir:**
Documento Criado

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/133468892-56adc513-f3a3-44c8-8f1c-f52d651607cb.png)

**Comment by wendell-codata** [comment]
Foi verificado antecipadamente que ao remover a permissão de Arquivos auxiliares o mesmo esconde o conteudo, porém não a caixa.

**Comment by allyssoncruz** [comment]
issue duplicada
