### ISSUE TITLE
Documento Capturado não abre

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#112]
**Descrição:**
Documento Capturado (CAP) não abre.

**Passos Para Reproduzir:**
mesa virtual > documento CAP

**Usuário que fez o teste:**
Halamo

**Ambiente:**
homolog

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/133512801-9ad69c20-a712-499f-9d24-eaf15236272d.png)

**Comment by michelrisucci-codata** [comment]
Os tipos e formas de documentos para documento externos estavam duplicados.
Foi necessário remover o `id_forma_doc = 99`.

```sql
delete from ex_forma_documento where id_forma_doc = 99;
delete from ex_tp_forma_doc where id_forma_doc = 99;
```
