### ISSUE TITLE
Documento assinado e não mostra os botões

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#113]
**Descrição:**
O Documento ja foi assinado, porém, não esta aparecendo os botões. Ex. assinar, anexar...

**Passos Para Reproduzir:**
mesa virtual > documento SAD-OFI-2021/00779

**Usuário que fez o teste:**
Halamo

**Ambiente:**
homolog

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/133514211-385bf005-31df-415d-b278-5f015c7f821d.png)

**Comment by wendell-codata** [comment]
Após realizar o DEBUG, foi identificado que a tabela 'ex_movimento' não foi importada, portanto ao realizar a montagem os menus que movimentam o documento, os mesmos só aparecerão em função do conteúdo da referida tabela.
Falei com Francisco Porfírio que está ciente da não importação dos dados e esta corrigindo.
Esta tarefa só poderá ser verificada após a importação ocorrer com sucesso!

Sugiro enviar esta tarefa para proxima Sprint

**Comment by wendell-codata** [comment]
Aguardando solução de migração para conclusão da tarefa acima.

**Comment by wendell-codata** [comment]
Realizada reunião nesta data (04/10/2021) com Team. Também foi contactado Francisco Porfírio sobre a migração que resultará na auto-correção desta tarefa.

**Comment by wendell-codata** [comment]
Após correta migração do banco a tarefa auto-corrigiu.
