### ISSUE TITLE
Erro ao assinar documento

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#114]
**Descrição:**
Esta ocorrendo erro ao anexar e assinar o documento com senha

**Passos Para Reproduzir:**
criar documento > anexar > assinar

**Usuário que fez o teste:**
Allysson

**Ambiente:**
homolog

Evidências:

![image](https://user-images.githubusercontent.com/56409226/133620898-fcc56c4b-4923-4d0d-97a3-eb2bfac45598.png)

**Comment by caiosantos-codata** [comment]
@michelrisucci-codata, 
aparentemente, esta issue está relacionada à issue #92 .

além disso, a descrição está um pouco ambígua. O erro ocorre ao assinar o **ANEXO** do documento, e não o documento em si.

**Comment by caiosantos-codata** [comment]
@allyssoncruz, 
qual é a diferença entre assinar via botão 'Assinar'  e o link 'Assinar' (que está abaixo de 'Excluir') na coluna descrição?

**Comment by michelrisucci** [comment]
> @michelrisucci-codata,
> aparentemente, esta issue está relacionada à issue #92 .
> 
> além disso, a descrição está um pouco ambígua. O erro ocorre ao assinar o **ANEXO** do documento, e não o documento em si.

Relativo ao problema de leitura de anexos disposto na issue #112

**Comment by michelrisucci-codata** [comment]
> @michelrisucci-codata,
> aparentemente, esta issue está relacionada à issue #92 .
> 
> além disso, a descrição está um pouco ambígua. O erro ocorre ao assinar o **ANEXO** do documento, e não o documento em si.

Relativo ao problema de leitura de anexos disposto na issue #112.

**Comment by michelrisucci** [comment]
Correção implementada.

Testei com assinatura de ANEXOS e visualização (que estava quebrada) em ANEXOS e ARQUIVOS AUXILIARES.

![correcao-pbdoc](https://user-images.githubusercontent.com/1094167/133831374-fefa0c0c-61c8-47dd-96f6-57b87ad14f3b.png)

**Comment by michelrisucci-codata** [comment]
Correção implementada.

Testei com assinatura de ANEXOS e visualização (que estava quebrada) em ANEXOS e ARQUIVOS AUXILIARES.

![correcao-pbdoc](https://user-images.githubusercontent.com/1094167/133831374-fefa0c0c-61c8-47dd-96f6-57b87ad14f3b.png)
