### ISSUE TITLE
Erro a cancelar VIAS

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#120]
**Descrição:**
Ao criar um documento e criar vias, se for necessario cancelar apenas uma via o usuarios não consegue. 
Ex. Na imagem abaixo selecionei e tentei cancelar apenas a "VIA C", dai o sistema cancela todas.

**Passos Para Reproduzir:**
Criar documento > assinar > criar vias varis vias > depois tentar cancelar apenar uma
O comportamento era pra cancelar apenas a selecionada

Usuário que fez o teste:
Karol

Ambiente:
https://homolog.pbdoc.pb.gov.br/

Evidências:

![image](https://user-images.githubusercontent.com/56409226/133995511-8bf24e27-f210-4cf2-a6c7-068ed6b1ddbf.png)

![image](https://user-images.githubusercontent.com/56409226/133995587-ec32d0bf-69fd-4124-a53a-50bdf71a6317.png)

![image](https://user-images.githubusercontent.com/56409226/133995630-898cd2a3-2881-4482-addb-a86f455af959.png)

**Comment by caiosantos-codata** [comment]
Após reunião de alinhamento no dia 04/10/2021, foram feitos os seguintes esclarecimentos:

1- A descrição e os prints anexados mencionam a ação 'Cancelar' para cancelar uma via. Isso é um equívoco, já que a ação de cancelar é para cancelar o documento pai que contém as vias. 
2- Existe a opção 'cancelar via'. Porém, ela só fica habilitada quando o documento está 'finalizado' e não 'assinado'.

Então, é possível listar as seguintes melhorias:

- [ ] Listar vias após documento finalizado. 
- [ ] Habilitar ação 'Cancelar Via' mesmo após documento assinado.

cc: @allyssoncruz
