### ISSUE TITLE
Erro ao visualizar documento na pagina principal

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#125]
**Descrição:**
Erro ao visualizar documento na pagina principal

**Passos Para Reproduzir:**
Anexar um documento e tentar visualizar na pagina principal

**Usuário que fez o teste:**
Simone

**Ambiente:**
homolog

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/134086373-20f1f936-d6e1-4ade-8ddd-0efa3ff9706d.png)

**Comment by michelrisucci-codata** [comment]
Resolvido na issue #114
