### ISSUE TITLE
Duplicidade em documentos arquivados

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#126]
**Descrição:**
Após o documento arquivado, aparece duas opções para desarquivar "desarq. corrente" e "desfazer arquivamento corrente" se for a mesma funcionalidade acredito que esta duplicado com nome diferente .

**Passos Para Reproduzir:**
clicar em "arq. corrente" 

**Usuário que fez o teste:**
Simone

**Ambiente:**
homolog

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/134087321-25f2e74b-158d-4ea8-b63e-37dea5b34957.png)

**Comment by wendell-codata** [comment]
Realizar ocultamento em Cadastro de configuração em Movimentação, logo após o item "Desarquivamento" conforme abaixo;

![image](https://user-images.githubusercontent.com/84041326/135100974-6b190f9a-81ce-4306-b57f-ea4b415f6e23.png)
