### ISSUE TITLE
Usuário é marcado com perfil de interessado

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#128]
**Descrição:**
- Quando o usuário é marcado como Interessado, em algum expediente/processo administrativo, este deveria apenas visualizar a movimentação do documento. O usuário é marcado com perfil de interessado as funcionalidades , ANOTAR, DEFINIR PERFIL, RECLASSIFICAR, DUPLICAR, RESTRIÇÃO DE ACESSO, ficam disponiveis. Quando na verdade o interessado só poderia visualizar. 

**Passos Para Reproduzir:**
Documento > Definir Marcador

**Usuário que fez o teste:**
Simone

**Ambiente:**
homolog

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/134217001-05346fcf-2762-461b-8310-dccfc4faa36b.png)

**Comment by wendell-codata** [comment]
A tarefa deverá ser realizada em homologação e registrada no Issue. Posteriormente será realizada em Produção.
No momento há o IMPEDIMENTO, devido ao sistema não estar conectando com o Banco de Dados. O problema foi causado devido a uma manutenção realizada nos servidores no ultimo fim de semana 25 e 26/09/2021.
