### ISSUE TITLE
Documento publico só pode ser acessado para visualização

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#129]
**Descrição:**
Quando os documentos ficam com o acesso publico, e alguém faz a busca para tentar visualizar esses documentos, mesmo não sendo da mesma secretaria, esta conseguindo inserir informações em um documento que seria apenas para visualização, e ainda consegue fazer o downloand por completo. O documento quando esta publico ele só pode ser acessado para visualização.  Foi feito o teste pesquisando um documento da Casa Militar do Governador, com um usuário da Secretaria de Administração. e Consegui , ANOTAR, DEFINIR PERFIL, RECLASSIFICAR, DUPLICAR, RESTRIÇÃO DE ACESSO, e ainda baixar o arquivo completo 

**Passos Para Reproduzir:**
Acessar um documento publico

**Usuário que fez o teste:**
Simone

**Ambiente:**
homolog

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/134235604-a4fe6eba-9962-4d6a-9eb8-616d83962380.png)

![image](https://user-images.githubusercontent.com/56409226/134235647-828fbe6c-63a2-431b-9a6f-8e935c516f0b.png)

![image](https://user-images.githubusercontent.com/56409226/134235710-8fc2f8e4-5587-42a9-beec-05efc372408b.png)

**Comment by caiosantos-codata** [comment]
@allyssoncruz, 
> O documento quando esta publico ele só pode ser acessado para visualização.
Nesse caso, não deveria aparecer nenhuma ação (primeira região destacada no print 2)?
ou quais ações deveriam estar habilitadas? a ação 'Ver Documento Completo', por exemplo?

cc: @wendell-codata

**Comment by caiosantos-codata** [comment]
@wendell-codata, 
a solução desta issue passa por 'cadastro de configurações'?

**Comment by caiosantos-codata** [comment]
Segundo Karol, as ações que deveriam ser habilitadas são: 'DUPLICAR', 'HISTÓRICO', 'VER DOCUMENTO COMPLETO'
