### ISSUE TITLE
Esconder a opção "Publicar no portal da transparência"

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#132]
**Descrição:**
Esconder a opção "Publicar no portal da transparência". obs: o campo esta com erro ao enviar

**Passos Para Reproduzir:**
Criar documento > campo "Publicar no portal da transparência"

**Usuário que fez o teste:**
Jozelma

**Ambiente:**
homolog

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/134240197-039b9fff-2aef-4c92-918b-8d83969c8cc7.png)

**Comment by luizfonseca830** [comment]
Acessando o menu Módulos>Documentos
![tela1](https://user-images.githubusercontent.com/6956215/135656849-bbbf5ab1-d3f5-4a12-8a8b-8409c33b02cf.png)
Depois Ferramentas>Cadastro de configurações
![tela2](https://user-images.githubusercontent.com/6956215/135656991-6d886d92-663b-4890-aa81-3e0ff8de7b47.png)
É necessario selecionar o tipo de movimentação Publicação Portal de Transparência e logo apos pressionar ok.
![tela3](https://user-images.githubusercontent.com/6956215/135657119-b2119abc-8d49-42c5-9ff2-1463358ae9b2.png)
