### ISSUE TITLE
Mostrar data no tramite

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#145]
**Descrição:**
 Ao tramitrar um documento e colocar a data de devolução. A primeira unidade recptora recebe com a data de devolução do documento, caso seja necessario que essa unidade tramite para outro setor, a segunda unidade não recebe que o alerta que o documento tem uma data para ser devolvido.
 Seria necessario que durante todo o tramite do documento fosse mostrado que o mesmo tem uma data para ser devolvido ao setor que o criou. 

**Passos Para Reproduzir:**
 tramitrar um documento e colocar a data de devolução

**Usuário que fez o teste:**
Karol -  Item 28

**Ambiente:**
homolog

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/135458434-f09a9067-b1ff-4c0d-9fd4-89e77ad5e1eb.png)

![image](https://user-images.githubusercontent.com/56409226/135458497-4d899b6b-8ccf-47ee-a702-16ba06b80ad3.png)

![image](https://user-images.githubusercontent.com/56409226/135458578-7dd1ff6e-0729-4277-88ac-1b51adab8e51.png)

**Comment by caiosantos-codata** [comment]
Salvo engano, a versão v9 também apresenta esse comportamento. 
Por isso a tag feature parece ser mais indicada.
