### ISSUE TITLE
[PRIORITÁRIA] Pagina inicial como para abrir o quadro quantitativo

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#151]
**Descrição:**
A pagina inicial está configurada como para abrir o quadro quantitativo, onde na versão 9 a pagina inicial é a mesa virtual.

**Passos Para Reproduzir:**
pagina inicial

**Usuário que fez o teste:**
Pablo - Item 39

**Ambiente:**
homolog

**Evidências:**

Versão 10
![image](https://user-images.githubusercontent.com/56409226/135990302-9b341721-9c60-4e6a-b89e-53fbfc2fc16a.png)

Versão 9
![image](https://user-images.githubusercontent.com/56409226/135990423-c0a4cbb5-8db6-4599-aae9-38834fb0a9fe.png)

**Comment by wendell-codata** [comment]
Alterado no OPENSHIFT em ambiente de homologação... 

Realizar alteração também em ambiente de produção.
