### ISSUE TITLE
SUBSTITUTO: O usuário pode selecionar qualquer outro para assinar em substituição.

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#154]
**Descrição:**
O usuário pode selecionar qualquer outro para assinar em substituição.
Não aparece uma listas com os nomes das pessoas que o usuário tem permissão em assinar como substituto. Ficando aberto para selecionar qualquer um .

**Passos Para Reproduzir:**
Selecionr substituto

**Usuário que fez o teste:**
Simone - Item 41

**Ambiente:**
homolog

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/135992546-dd4416bd-11da-4e42-8ce8-e75813388266.png)

![image](https://user-images.githubusercontent.com/56409226/135992617-a4a5e528-e658-459f-b85f-7e111a643d00.png)

**Comment by wendell-codata** [comment]
Alysson,
Essa função deve ser comparada com a versão 9 para determinar se é uma Feature, Bug ou se o comportamento ja era esse.

**Comment by caiosantos-codata** [comment]
Estou assumindo que esta issue tem a ver com a permissão ‘Gerenciar substitutos', que pode ser encontrada via menu 'Gestao de Identidade -> configurar permissões'

Nesse caso, após habilitar tal permissão, o correto seria listar apenas usuários que já estão cadastrados como substitutos.
