### ISSUE TITLE
O documento pode ser totalmente alterado por qualquer um dos cossignatários

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#155]
**Descrição:**
- imagem 1: O cossignatário consegue editar o documento e assinar antes do responsável pela assinatura marcado na elaboração do documento. 
- Imagem 2: mesmo com o documento já assinado a opção "assinar" ainda fica visível para o cossignatário. Apesar de não conseguir assinar novamente. 
- Imagem 3: não fica registrado no histórico a edição feita pela cossignatário. Mostra apenas que foi assinado 

O documento pode ser totalmente alterado por qualquer um dos cossignatários, e não fica registrado quem fez as alterações

Usuário que fez o teste:
Simone - Item 17

**Ambiente:**
homolog

**Evidências:**

Imagem 1
![image](https://user-images.githubusercontent.com/56409226/135993593-3825afdf-4f42-4690-b793-7e0bb2aa66b7.png)

Imagem 2
![image](https://user-images.githubusercontent.com/56409226/135993669-f5b65213-7470-4e88-aeb7-1ab37cbaac30.png)

Imagem 3
![image](https://user-images.githubusercontent.com/56409226/135993769-de88bad4-1c73-40d1-a203-14a51ae2f881.png)

**Comment by wendell-codata** [comment]
Alysson,
Essa função deve ser comparada com a versão 9 para determinar se é uma Feature, Bug ou se o comportamento já era esse.

**Comment by allyssoncruz** [comment]
Conforme conversa com Simone esta ocorrendo em produção.
