### ISSUE TITLE
Abrir Manual Web no PBdoc link: https://portal.pbdoc.pb.gov.br/manual

### ISSUE THREAD

**Issue by michelrisucci-codata** [codata-gedes/pbdoc#16]
Caminho: APOSTILA SIGA-DOC
URL: https://homolog.pbdoc10.codata.pb.gov.br/siga/arquivos/apostila_sigaex.pdf
Não conformidade: ABERTURA DE MANUAL SIGA TRF2

**Comment by wendell-codata** [comment]
Resolvido na issue #15
