### ISSUE TITLE
Desabilitar funções

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#167]
**Descrição:**

Desabilitar as seguintes funções:

Publicar no portal da transparência;
Auntenticar;
Restrição de Acesso; 
Gerar Protocolo

**Passos Para Reproduzir:**
Criar documento

**Usuário que fez o teste:**
Simone - S1

**Ambiente:**
homolog versão 10

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/137741007-fffeaacb-ba72-4755-8ec5-a8b7b1d720ef.png)

**Comment by wendell-codata** [comment]
Realizado a criação do script a ser executado na pos migração.. foi incluido na Issu #170.
