### ISSUE TITLE
Nome incorreto nas configurações

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#195]
**DEscrição**

O nome esta incorreto nas configurações.

obs:  Essa opção não aparece para todos.

Macarrão > Marcação

**Evidência**

![image](https://user-images.githubusercontent.com/56409226/140536986-a7009d70-260b-449a-9666-7a2eb548d9a2.png)

**Comment by wendell-codata** [comment]
Foi realizada a verificação no sistema ao acessar com meu Usuario e Senha, porém não foi identificado o problema relatado, conforme print de tela abaixo. Provavelmente um problema de cache. Foi orientado limpaz o cache do navegado e acessar. Também foi realizado um teste com usuario do @allyssoncruz e também não foi verificado problemas.

![image](https://user-images.githubusercontent.com/84041326/140744818-ab6fc029-3d54-4517-9572-9cddf86863df.png)
