### ISSUE TITLE
Logo do estado não esta completa

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#213]
**Descrição**

logo do estado não esta completa

![image](https://user-images.githubusercontent.com/56409226/145082370-977f8672-5be5-4816-b9b5-b3b965aa23d1.png)

**Comment by michelrisucci-codata** [comment]
Corrigido. Atualização de produção disparada agora - deve entrar em alguns minutos.

![image](https://user-images.githubusercontent.com/83982953/145376773-b7f40df2-690c-4163-b097-ed8dc8a570f3.png)
