### ISSUE TITLE
Verificar paginação dos processos na 'Pesquisa Avançada' na v10

### ISSUE THREAD

**Issue by evandroalbuquerque-codata** [codata-gedes/pbdoc#216]
Paginação não funciona na **'Pesquisa Avançada'** de documentos. Problema ocorre ao mudar de página (Ocorrido com a **PGE** na v9).

**Comment by michelrisucci-codata** [comment]
Não conseguimos reproduzir o bug na v10.
Paginação estava funcionando corretamente.
