### ISSUE TITLE
Garantir que funcionalidades de arquivamento em lote não estejam disponíveis agora

### ISSUE THREAD

**Issue by michelrisucci-codata** [codata-gedes/pbdoc#228]
- DOCUMENTOS > ARQUIVAR INTERMEDIÁRIOS EM LOTE
- DOCUMENTOS > ARQUIVAR PERMANENTE EM LOTE
- DOCUMENTOS > ARQUIVAR INTERMEDIÁRIOS EM LOTE W PERMANENTE EM LOTE

Testes foram feitos com o usuário de Marcelo (GEDES)

**[IMPORTANTE] Garantir que as permissões no banco de dados não estejam habilitando estas opções para os usuários.**

**Comment by caiosantos-codata** [comment]
@michelrisucci-codata, 

As funcionalidades listadas são habilitadas de acordo com a função [podeArquivarPermanentePorConfiguracao](https://github.com/codata-gedes/pbdoc/blob/d2ab41f98aeea620cb9ff6d6f761a313ff5c8b76/siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/FuncoesEL.java#L120). Essa função depende dos valores registrados nas tabelas `cp_configuracao` e `ex_configuracao`.

uma solução via SQL é a seguinte (baseado nesse [comentário](https://github.com/codata-gedes/pbdoc/issues/170#issuecomment-947793760) da issue #170)

```sql
-- inserir nova cp_configuracao
insert into cp_configuracao (his_dt_ini, id_sit_configuracao, id_tp_configuracao, his_idc_ini, his_id_ini) values (
    current_date, 
    2, -- situação 'não pode'
    1, -- TIPO_CONFIG_MOVIMENTAR 'Movimentar' (vide classe `CpTipoConfiguracao`)
    2, -- ?
    (select id_configuracao + 1 from cp_configuracao order by id_configuracao desc limit 1)) -- id incremental
;

-- inserir nova ex_configuracao associada à cp_configuracao criada acima
INSERT INTO siga.ex_configuracao (id_configuracao_ex, id_tp_mov) VALUES (
    (select id_configuracao from cp_configuracao order by id_configuracao desc limit 1),  --id recem criado
    19 -- TIPO_MOVIMENTACAO_ARQUIVAMENTO_PERMANENTE (vide classe `ExTipoConfiguracao`)
);
```

uma alternativa seria via menu `Ferramentas` -> `Cadastro de Configurações` (baseado nesse [comentário](https://github.com/codata-gedes/pbdoc/issues/167#issuecomment-946152642)):

- Tipo de configuração: "Movimentar"
- Situação: "Não Pode"
- Tipo de Movimentação: "Recolhimento ao Arq. Permanente"

**Comment by michelrisucci-codata** [comment]
> @michelrisucci-codata,
> 
> As funcionalidades listadas são habilitadas de acordo com a função [podeArquivarPermanentePorConfiguracao](https://github.com/codata-gedes/pbdoc/blob/d2ab41f98aeea620cb9ff6d6f761a313ff5c8b76/siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/FuncoesEL.java#L120). Essa função depende dos valores registrados nas tabelas `cp_configuracao` e `ex_configuracao`.
> 
> uma solução via SQL é a seguinte (baseado nesse [comentário](https://github.com/codata-gedes/pbdoc/issues/170#issuecomment-947793760) da issue #170)
> 
> ```sql
> -- inserir nova cp_configuracao
> insert into cp_configuracao (his_dt_ini, id_sit_configuracao, id_tp_configuracao, his_idc_ini, his_id_ini) values (
>     current_date, 
>     2, -- situação 'não pode'
>     1, -- TIPO_CONFIG_MOVIMENTAR 'Movimentar' (vide classe `CpTipoConfiguracao`)
>     2, -- ?
>     (select id_configuracao + 1 from cp_configuracao order by id_configuracao desc limit 1)) -- id incremental
> ;
> 
> -- inserir nova ex_configuracao associada à cp_configuracao criada acima
> INSERT INTO siga.ex_configuracao (id_configuracao_ex, id_tp_mov) VALUES (
>     (select id_configuracao from cp_configuracao order by id_configuracao desc limit 1),  --id recem criado
>     19 -- TIPO_MOVIMENTACAO_ARQUIVAMENTO_PERMANENTE (vide classe `ExTipoConfiguracao`)
> );
> ```
> 
> uma alternativa seria via menu `Ferramentas` -> `Cadastro de Configurações` (baseado nesse [comentário](https://github.com/codata-gedes/pbdoc/issues/167#issuecomment-946152642)):
> 
>     * Tipo de configuração: "Movimentar"
> 
>     * Situação: "Não Pode"
> 
>     * Tipo de Movimentação: "Recolhimento ao Arq. Permanente"

Caio, vou avaliar localmente esta solução hoje.
Funcionando, a gente dispara com Porfírio pro ambiente de pré-produção.
Obrigado.
