### ISSUE TITLE
Mensagens de Informação para o Usuário

### ISSUE THREAD

**Issue by wendell-codata** [codata-gedes/pbdoc#25]
Inserir mensagens de (sucesso ou falha) para os Usuários após realização de Inclusão, Alteração ou Exclusão.

**Comment by luizfonseca830** [comment]
é meu

**Comment by luizfonseca830** [comment]
No aguardo das definições de algumas telas que precisam dessa mensagem.

**Comment by wendell-codata** [comment]
Todos aviso para Cadastro e Edição que não existem.

- Cadastro de Orgão
- Cadastro de Unidade
- Cadastro de Cargo
- Cadastro de Função de Confiança
- Cadastro de Pessoa
- Envio de e-mail
- Identidade
- Cadastro de quaisquer documentos

Esses são os que demandam maior interação com o usuário final.
