### ISSUE TITLE
Remover Botão Ver Impressão e Incluir botão Voltar

### ISSUE THREAD

**Issue by wendell-codata** [codata-gedes/pbdoc#35]
Incluir ainda Botão Voltar conforme figura abaixo e remover botãor Ver Impressão.

Ao retornar não poderá retornar para o form, mas para a pagina do documento criado, evitando criar um segundo documento ao retornar.

![image](https://user-images.githubusercontent.com/84041326/127048465-e829cb48-412a-4a7b-bd07-31af3a3a39a1.png)

**Comment by michelrisucci-codata** [comment]
Em reunião hoje decidimos não mexer nesta _issute_.
Vamos fechá-la e reabriremos se for necessário.

close #35
