### ISSUE TITLE
Senha do usuario aparecendo no log do Openshift

### ISSUE THREAD

**Issue by wendell-codata** [codata-gedes/pbdoc#46]
Ao inserir usuario e senha, quando ocorre erro de login o nome do usuario e a senha é exibido no log do Openshift.

**Comment by michelrisucci-codata** [comment]
Apenas ajuste de logging do Apache CXF no `standalone.xml`.
O nível de logging estava em DEBUG e, por isso, logava os parâmetros de qualquer requisição que utilizasse este _framework_. Nívels como `INFO` ou `WARN` já não mostram mais. O trecho abaixo mostra como foi deixada a configuração agora:

```xml
            <logger category="org.apache.cxf">
                <level name="WARN"/>
            </logger>
```
