### ISSUE TITLE
Não carrega cargo em Cadastro de Pessoa (listar)

### ISSUE THREAD

**Issue by wendell-codata** [codata-gedes/pbdoc#52]
Na tela abaixo, ao clicar em cargo, não é listado os cargos cadastados, fazendo necessário clicar em pesquisar para em seguida listar cargo.

![image](https://user-images.githubusercontent.com/84041326/129622790-4670bf42-1e26-42f8-99b3-b00a5608398f.png)

**Comment by luizfonseca830** [comment]
Eu fiz uns teste está normal essa questão

**Comment by wendell-codata** [comment]
Também fiz a validação e provavelmente auto-corrigiu devido a uma tarefa anterior.
Encerrando Issue.
