### ISSUE TITLE
Erro ao tentar colar texto - Criar novo documento

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#60]
**Descrição:**
Ao Criar um novo documento no campo "Texto a ser Inserido", não esta deixando "colar" algum texto externo pelos botões da ferramenta ou com o botão direito do mouse.

**Passos Para Reproduzir:**
Criar Novo > "Texto a ser Inserido"

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/130257100-351ba863-ecad-4c3d-962a-c85778221685.png)

**Comment by michelrisucci-codata** [comment]
@allyssoncruz isto é uma limitação dos browsers modernos.
Por uma questão de segurança, tanto o Chrome quanto o Firefox não permitem acesso à Área de Transferência (setor do sistema operacional que guarda tudo que se faz "Ctrl+C").

A própria aplicação já mostra um aviso de que é recomendado usar "Ctrl+V" para isto.

![image](https://user-images.githubusercontent.com/83982953/130665323-b7c21427-b7b3-4f40-ab46-f1acc3930087.png)
