### ISSUE TITLE
Novos perfis em Definição de Perfil

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#61]
**Descrição:**
Na nova versão esta aparecendo dois novos perfis: Fiscal tec. e Fiscal ADM. Gostaria de saber se vai continuar porque se for o analista Marcelo precisa de orientação sobre as atribuições desses perfis pois ele precisa para poder documentar.

**Passos Para Reproduzir:**
Criar Novo > "Definir Perfil" 

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/130258182-80abc714-9ca9-409c-8fa8-d576d6c83d69.png)

![image](https://user-images.githubusercontent.com/56409226/130258209-bf8934fe-de71-4067-a381-a4fc590a7362.png)

**Comment by michelrisucci-codata** [comment]
N/A
