### ISSUE TITLE
Documento Criado - Ver documento completo

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#67]
Descrição:
Ao clicar em abrir o documento so mosta a pagina 1 de 1 sendo que existem mais paginas a visualizar

Passos Para Reproduzir:
Documento criado - ver documento completo

Evidências:
n/a

**Comment by michelrisucci-codata** [comment]
@allyssoncruz não consegui reproduzir este problema. Ao tentar visualizar o documento completo, tive o PDF do documento completo:

![image](https://user-images.githubusercontent.com/83982953/131352391-5798d72c-2170-4056-b0f9-25ecf028b8a7.png)
