### ISSUE TITLE
Anexo em pdf maiores que 5Mb dão tela de erro

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#71]
**Descrição:**
O limite máximo de 10Mb para arquivos em PDF apresenta tela de erro. Após vários testes vi que o tamanho máximo está em 5Mb

**Passos Para Reproduzir:**
Documento criado - ver documento completo

**Evidências:**
n/a

**Comment by michelrisucci-codata** [comment]
O problema ocorria porque a property lida no `standalone.xml` estava errada.

Onde tinha:
```xml
<property name="pdf.tamanho.maximo" value="50000000" />
```

Substituir por:
```xml
<property name="sigaex.pdf.tamanho.maximo" value="10485760" />
```

**IMPORTANTE: o `name` da _property_ é diferente da anterior. Precisa estar prefixada com `sigaex.` conforme descrito na linha acima.**
