### ISSUE TITLE
Criar documento - Campos obrigatórios

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#73]
**Descrição:**
Ao criar documento não esta validando os campos obrigatórios como: Classificação e Assunto.

**Passos Para Reproduzir:**

Criar Documento

**Evidências:**
n/a

**Comment by caiosantos-codata** [comment]
@allyssoncruz, 
ao testar, verifiquei que o campo 'Assunto' (antigo 'Descrição') está configurado como obrigatório.
