### ISSUE TITLE
Janela arquivos Auxiliares

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#78]
**Descrição:**
Não era pra esta aparecendo a janela "arquivos auxiliares"

**Passos Para Reproduzir:**
Ao criar um documento

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/130828164-a5147a46-b946-461a-8951-0715cf96152c.png)

**Comment by caiosantos-codata** [comment]
Aparentemente, esta issue foi duplicada com a #189, que, por sua vez, foi corrigida no [commit]( https://github.com/codata-gedes/pbdoc/commit/ff32d4879113f2880c2d448cfa0783644be15b16).

Para desabilitar a janela "arquivos auxiliares", é preciso:
1- no menu 'Ferramentas' -> 'Cadastro de Configurações', incluir  nova configuração do 'Tipo de Configuração' **Movimentar**;
2- na página seguinte, escolher o 'Tipo de Movimentação'  **Anexação de Arquivo Auxiliar**  e configurar a 'Situação' como **Não Pode**
