### ISSUE TITLE
Texto do documento despacho padrão

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#91]
**Descrição:**
Documento Despacho: Está definido o texto do despacho padrão: Para as providências cabíveis. Nesse caso mesmo que o usuário escreva algo no campo de escrita livre, ficará gravado o padrão. Ideal: que neste campo seja definido como padrão: Outros

**Passos Para Reproduzir:**
Criar novo > documento despacho

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/132551972-c2be5d65-98e2-4884-b59b-4916e9d9c7ea.png)

**Comment by caiosantos-codata** [comment]
@allyssoncruz, 

Uma solução para este issue é a modificação do template freemarker via menu 'Ferramentas -> Cadastro de Modelos'.
Especificamente, modificar a linha 21 do templete para:
`[#assign texto_padrao = "[Outro]"/]`

**Comment by michelrisucci** [comment]
@halamo-codata isso me parece ser algo que só ocorre na aplicação zerada, uma vez que os templates de produção já foram modificados e estão estabilizados. Seguir com essa issue?

**Comment by allyssoncruz** [comment]
Essa issue ja esta ok.

![image](https://user-images.githubusercontent.com/56409226/133326449-2d5e263c-a0fc-4a25-94a9-332b3de3c500.png)

**Comment by michelrisucci-codata** [comment]
@allyssoncruz você testou no ambiente de homologação, num foi isso??

É importante saber essas diferenças.
Você abriu o ticket porque estava usando o banco do SUPORTE v10 que é zerado.
Agora que testou na versão migrada de produção está apresentando o comportamento correto.

Lembrar de informar, nas issues, qual ambiente testou pra deixar claro. Pode influenciar no prosseguimento ou não das correções.
