### ISSUE TITLE
[ALTA]Erro ao clicar em Assinar documento e assinar anexo com Certificado Digital

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#92]
**Descrição:**
Anexação de Arquivo – Geral: Erro ao clicar em Assinar Em Anexos Pendentes de Assinatura, aparece o link: Assinar / Autenticar 
Assinar documento

**Passos Para Reproduzir:**
criar documento > assinar > assinar
Criar documento : anexar arquivo > assinar

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/132572009-d0285b4d-c06e-44c0-8ed4-54ea76b39cc4.png)

![image](https://user-images.githubusercontent.com/56409226/132572240-6606995a-0e59-4431-b8ce-517535d0fc29.png)

**Comment by michelrisucci-codata** [comment]
Vou fechar este ticket porque a assinatura digital foi resolvida na issue [#45] hoje.
