### ISSUE TITLE
Documento temporario mudando de comportamento sem estar assinado

### ISSUE THREAD

**Issue by allyssoncruz** [codata-gedes/pbdoc#95]
**Descrição:**
BOTÃO finalizar: Ao clicar em "finalizar" o documento deixa de ser TMP para ter caracteristicas de documento assinado "sem estar assinado" 

**Passos Para Reproduzir:**
Criar documento

**Evidências:**

![image](https://user-images.githubusercontent.com/56409226/132574661-2865656a-c492-4a1d-84c6-62f7c0f94a56.png)

![image](https://user-images.githubusercontent.com/56409226/132574685-4ff13db2-55db-437a-98e6-31ee8640b652.png)

**Comment by caiosantos-codata** [comment]
@allyssoncruz , 
poderia dar mais detalhes sobre qual é o comportamento correto para a ação 'finalizar'?

**Comment by allyssoncruz** [comment]
bom dia, em conversa com Marcelo esse comportamento esta correto, desconsiderar essa issue.
